"""
add mandatory reason to excluded_project

Revision ID: 5ddd92d15c8f
Revises: c5036babd7c2
Create Date: 2026-03-11 10:38:28.432979
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ddd92d15c8f"
down_revision = "c5036babd7c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excluded_project",
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=False,
            server_default="Legacy exclusion (reason not recorded)",
        ),
    )
    op.alter_column("excluded_project", "reason", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("excluded_project", "reason")
    # ### end Alembic commands ###
