name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Pack Rock image
    runs-on: ubuntu-latest
    outputs:
      rock: ${{ steps.rockcraft.outputs.rock }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pack Rock
        id: rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          rockcraft-channel: stable
          verbosity: brief

      - name: Upload Rock artifact
        uses: actions/upload-artifact@v4
        with:
          name: rock-image
          path: ${{ steps.rockcraft.outputs.rock }}

      - name: Set image URL
        id: image_url
        run: |
          IMAGE_URL=ghcr.io/canonical/canonical-cla:$(date +%s)-${GITHUB_SHA:0:7}
          echo "url=$IMAGE_URL" >> $GITHUB_OUTPUT
          echo -e "> [!NOTE]\n> The image URL is $IMAGE_URL" >> $GITHUB_STEP_SUMMARY

      - name: Push to GHCR
        run: skopeo --insecure-policy copy oci-archive:${{ steps.rockcraft.outputs.rock }} docker://${{ steps.image_url.outputs.url }} --dest-creds "canonical:${{ secrets.GITHUB_TOKEN }}"
