name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*.yaml"
env:
  ROCKCRAFT_JSON: rockcraft.json
  CHARMED_REPO: canonical/charmed-canonical-cla

jobs:
  build:
    name: Pack Rock image
    runs-on: ubuntu-latest
    outputs:
      rock: ${{ steps.rockcraft.outputs.rock }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rockcraft
        run: sudo snap install rockcraft --classic

      - name: Pack Rock
        id: rockcraft
        run: |
          sudo rockcraft pack -v --destructive-mode 2>&1 | tee rockcraft.log
          ROCK_IMAGE=$(cat rockcraft.log | sed -nE "s/Exported to OCI archive '(.*)'/\1/p")
          [ -z "$ROCK_IMAGE" ] && exit 1       
          echo "rock=$ROCK_IMAGE" >> $GITHUB_OUTPUT

      - name: Upload Rock artifact
        uses: actions/upload-artifact@v4
        with:
          name: rock-image
          path: ${{ steps.rockcraft.outputs.rock }}

      - name: Set image URL
        id: image_url
        run: |
          IMAGE_URL=ghcr.io/canonical/canonical-cla:$(date +%s)-${GITHUB_SHA:0:7}
          echo "url=$IMAGE_URL" >> $GITHUB_OUTPUT
          echo -e "> [!NOTE]\n> The image URL is \`$IMAGE_URL\`" >> $GITHUB_STEP_SUMMARY

      - name: Push to GHCR
        run: skopeo --insecure-policy copy oci-archive:${{ steps.rockcraft.outputs.rock }} docker://${{ steps.image_url.outputs.url }} --dest-creds "canonical:${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout ${{ env.CHARMED_REPO }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CHARMED_REPO }}
          path: charmed-repo
          ssh-key: ${{ secrets.CHARMED_CANONICAL_CLA_DEPLOY_PRIVATE_KEY }}

      - name: Update rockcraft.json in ${{ env.CHARMED_REPO }}
        run: |
          cd charmed-repo

          git config user.name "${{ github.actor }}-bot"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          yq e -i '.resources.app-image.upstream-source = "${{ steps.image_url.outputs.url }}"' metadata.yaml
          git add metadata.yaml
          git commit -m "Update Rock image ID: ${{ github.action_repository }}#${{ github.sha }}"

          git push
